DROP TABLE CONNECTIONS IF EXISTS;
CREATE TABLE CONNECTIONS
(
    "ID"              VARCHAR(120 CHAR) NOT NULL,
    "CONNECTION_NAME" VARCHAR(120 CHAR) NOT NULL,
    "URL"             VARCHAR(120 CHAR) NOT NULL,
    "USER_NAME"       VARCHAR(120 CHAR) NOT NULL,
    "PASSWORD"        VARCHAR(120 CHAR) NOT NULL,
    CONSTRAINT CONNECTIONS_PK PRIMARY KEY ("ID")
);

DROP TABLE TEST IF EXISTS;
CREATE TABLE TEST
(
    "TEST_ONE"   VARCHAR(120 CHAR) NOT NULL,
    "TEST_TWO"   VARCHAR(120 CHAR) NOT NULL,
    "TEST_THREE" DATE              NOT NULL,
    "TEST_FOUR"  VARCHAR(120)      NOT NULL,
    "TEST_FIVE"  DATE              NOT NULL,
    CONSTRAINT TEST_PK PRIMARY KEY ("TEST_ONE")
);

INSERT INTO TEST("TEST_ONE","TEST_TWO" ,"TEST_THREE", "TEST_FOUR", "TEST_FIVE") VALUES ('ONE', 'TWO', '2019-8-19', 'FOUR', '2019-8-19');

-- Simulate oracle database structure in H2 database
-- H2 System tables http://www.h2database.com/html/systemtables.html#information_schema
-- ORACLE System tables https://docs.oracle.com/database/timesten-18.1/TTSYS/systemtables.htm#TTSYS716
CREATE USER SYS PASSWORD 'PASSWORD';
GRANT ALTER ANY SCHEMA TO SYS;
CREATE SCHEMA SYS AUTHORIZATION SYS;

CREATE VIEW ALL_TABLES AS SELECT * FROM INFORMATION_SCHEMA.TABLES;
CREATE VIEW SYS.DBA_USERS AS SELECT SCHEMA_NAME AS USERNAME FROM INFORMATION_SCHEMA.SCHEMATA;
CREATE VIEW USER_TAB_COLS AS SELECT COLUMN_NAME, TYPE_NAME AS DATA_TYPE, TABLE_NAME FROM INFORMATION_SCHEMA.COLUMNS;
CREATE VIEW ALL_CONSTRAINTS AS SELECT * FROM INFORMATION_SCHEMA.CONSTRAINTS;