DROP TABLE CONNECTIONS IF EXISTS;
CREATE TABLE CONNECTIONS
(
    "ID"              VARCHAR2(120 CHAR) NOT NULL,
    "CONNECTION_NAME" VARCHAR2(120 CHAR) NOT NULL,
    "URL"             VARCHAR2(120 CHAR) NOT NULL,
    "USER_NAME"       VARCHAR2(120 CHAR) NOT NULL,
    "PASSWORD"        VARCHAR2(120 CHAR) NOT NULL,
    CONSTRAINT CONNECTIONS_PK PRIMARY KEY ("ID")
);

DROP TABLE TEST IF EXISTS;
CREATE TABLE TEST
(
    "TEST1" VARCHAR2(120 CHAR) NOT NULL,
    "TEST2" NUMBER NOT NULL,
    "TEST3" FLOAT  NOT NULL,
    "TEST4" LONG   NOT NULL,
    "TEST5" DATE   NOT NULL,
    CONSTRAINT TEST_PK PRIMARY KEY ("TEST1")
);

-- Simulate oracle database structure in H2 database
CREATE USER SYS PASSWORD 'PASSWORD';
GRANT ALTER ANY SCHEMA TO SYS;
CREATE SCHEMA SYS AUTHORIZATION SYS;

CREATE VIEW ALL_TABLES AS SELECT * FROM INFORMATION_SCHEMA.TABLES;
CREATE VIEW SYS.DBA_USERS AS SELECT SCHEMA_NAME AS USERNAME FROM INFORMATION_SCHEMA.SCHEMATA;
CREATE VIEW USER_TAB_COLS AS SELECT * FROM INFORMATION_SCHEMA.COLUMNS;
CREATE VIEW ALL_CONSTRAINTS AS SELECT * FROM INFORMATION_SCHEMA.CONSTRAINTS;