DROP TABLE CONNECTIONS IF EXISTS;
CREATE TABLE CONNECTIONS(
    "ID"              VARCHAR2(120 CHAR) NOT NULL,
    "CONNECTION_NAME" VARCHAR2(120 CHAR) NOT NULL,
    "URL"             VARCHAR2(120 CHAR) NOT NULL,
    "USER_NAME"       VARCHAR2(120 CHAR) NOT NULL,
    "PASSWORD"        VARCHAR2(120 CHAR) NOT NULL,
    CONSTRAINT CONNECTIONS_PK PRIMARY KEY ("ID")
);